### ISSUE TITLE
怎么关闭刷新头呢？

### ISSUE THREAD

**Issue by lutao2599** [123ufo/DWRefreshLayout#3]
请问下拉刷新时，怎么关闭刷新头呢？

**Comment by 123ufo** [comment]
dwRefreshLayout.setRefresh(false);

**Comment by lutao2599** [comment]
好的，在demo中看到了，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "123ufo/DWRefreshLayout"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月27日(星期五) 下午3:14
收件人:&nbsp;"123ufo/DWRefreshLayout"<DWRefreshLayout@noreply.github.com&gt;;
抄送:&nbsp;"追梦赤子"<1336440850@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [123ufo/DWRefreshLayout] 怎么关闭刷新头呢？ (#3)





 
dwRefreshLayout.setRefresh(false);
